.TH bias 1 16-AUG-2022 "Kozmix Go"

.SH NAME
bias \- calculate anode current and dissipation using the output transformer method

.SH SYNOPSIS
.B bias
Vcentre Vanode Rtransformer [Panode]

.SH DESCRIPTION
You use
.B bias
to calculate anode current and dissipation of a power valve by
measuring voltages on the output transformer. It takes three or four
arguments:

.SH OPTIONS
.TP
.B Vcentre
Voltage from the output transformer centre tap to ground, in Volts.
.TP
.B Vanode
Voltage from the anode to ground (this can usually be measured from
the transformer as well as from the correct pin on the valve socket),
in Volts.

.P
Both voltages are measured on a
.I live
amplifier that has had a couple of minutes to warm up and stabilise,
and with the volume at 0.

.TP
.B Rtransformer
DC resistance in Ohms between the centre tap and the anode, meansured
with the amplifier turned
.I off
(obviously). You might want to drain the filter capacitors before
doing this.

.P
Optionally followed by:

.TP
.B Panode
desired anode power dissipation in Watt. This will calculate the
voltage drop between centre tap and anode corresponding to this anode
current, for easy biasing.

Note that this is somewhat meaningless since changing the bias to
achieve this voltage drop is quite likely to change the anode voltage
which in its turn changes this calculation.


.SH EXAMPLE
.EX
$ ./bias 250 247.76 109 10
centre tap voltage            = 250 V
anode voltage                 = 247.8 V
output transformer resistance = 109 Ω
desired anode dissipation     = 10 W

voltage drop                  = 2.24 V
anode current                 = 20.55 mA
anode dissipation             = 5.092 W

desired voltage drop          = 4.399 V
.EE

.SH AUTHOR
svm

